using System.ComponentModel;

namespace WeatherApi
{
    public enum Language
    {
        [AmbientValue("af")]
        Afrikaans,
        [AmbientValue("al")]
        Albanian,
        [AmbientValue("ar")]
        Arabic,
        [AmbientValue("az")]
        Azerbaijani,
        [AmbientValue("bg")]
        Bulgarian,
        [AmbientValue("ca")]
        Catalan,
        [AmbientValue("cz")]
        Czech,
        [AmbientValue("da")]
        Danish,
        [AmbientValue("de")]
        German,
        [AmbientValue("el")]
        Greek,
        [AmbientValue("en")]
        English,
        [AmbientValue("eu")]
        Basque,
        [AmbientValue("fa")]
        Persian,
        [AmbientValue("fi")]
        Finnish,
        [AmbientValue("fr")]
        French,
        [AmbientValue("gl")]
        Galician,
        [AmbientValue("he")]
        Hebrew,
        [AmbientValue("hi")]
        Hindi,
        [AmbientValue("hr")]
        Croatian,
        [AmbientValue("hu")]
        Hungarian,
        [AmbientValue("id")]
        Indonesian,
        [AmbientValue("it")]
        Italian,
        [AmbientValue("ja")]
        Japanese,
        [AmbientValue("kr")]
        Korean,
        [AmbientValue("la")]
        Latvian,
        [AmbientValue("lt")]
        Lithuanian,
        [AmbientValue("mk")]
        Macedonian,
        [AmbientValue("no")]
        Norwegian,
        [AmbientValue("nl")]
        Dutch,
        [AmbientValue("pl")]
        Polish,
        [AmbientValue("pt")]
        Portuguese,
        [AmbientValue("pt_br")]
        Portugues,
        [AmbientValue("ro")]
        Romanian,
        [AmbientValue("ru")]
        Russian,
        [AmbientValue("sv")]
        Swed,
        [AmbientValue("se")]
        Swedish,
        [AmbientValue("sk")]
        Slovak,
        [AmbientValue("sl")]
        Slovenian,
        [AmbientValue("sp")]
        Espanole,
         [AmbientValue("es")]
        Spanish,
        [AmbientValue("sr")]
        Serbian,
        [AmbientValue("th")]
        Thai,
        [AmbientValue("tr")]
        Turkish,
        [AmbientValue("ua,")]
        uk,
        [AmbientValue("vi")]
        Vietnamese,
        [AmbientValue("zh_cn")]
        Chinese,
        [AmbientValue("zh_tw")]
        Taiwaneese,
        [AmbientValue("zu")]
        Zulu,
    }
}
